// src/app/menu/menu.component.ts
import {Component, ElementRef} from '@angular/core';

@Component({
  selector: 'app-menu',
  templateUrl: './menu.component.html',
  styleUrls: ['./menu.component.scss']
})
export class MenuComponent {
  appPages = [
    {
      title: 'Todos',
      url: '/todos',
      icon: 'list'
    },
    {
      title: 'Settings',
      url: '/settings',
      icon: 'settings'
    },
    {
      title: 'About',
      url: '/about',
      icon: 'info'
    }
  ];

  constructor(private elementRef: ElementRef) {
  }

  menuItemClicked() {
    this.elementRef.nativeElement.dispatchEvent(new Event('clicked'));
  }

}

<app-toolbar>Todo-App</app-toolbar>

<div role="listbox">
  <paper-item *ngFor="let p of appPages"
              [routerLink]="[p.url]"
              (click)="menuItemClicked()"
              class="border_bottom">
    <iron-icon [icon]="p.icon"></iron-icon>
    {{p.title}}
    <paper-ripple></paper-ripple>
  </paper-item>
</div>

// src/components/Menu.tsx
import React from 'react';
import {withRouter} from 'react-router-dom';
import {pages} from '../constants';
import {MenuComponentProps} from '../typings';

function MenuComponent(props: MenuComponentProps) {
    return (
        <div>
            <app-toolbar>Menu</app-toolbar>
            <div role="listbox">
                {Object.values(pages).map((page) => (
                    <paper-item
                        onClick={() => {
                            props.history.push(page.url);
                            props.closeDrawer();
                        }}
                        key={page.title}>
                        <iron-icon icon={page.icon}/>
                        {page.title}
                        <paper-ripple/>
                    </paper-item>
                ))}
            </div>
        </div>
    );
}

export default withRouter(MenuComponent);
